# CustomMessage v6.7 Config
# CompliantVersion 1.7.2～1.10.2
# ColorCodeList http://ess.khhq.net/mc/
# SoundList http://www.yuttyann44581.net/uploads/SoundList/
# OldSoundList http://www.yuttyann44581.net/uploads/OldSoundList/

## === APIモード === ##
# [true で有効 | false で無効]
# 初期: false
# APIだけを使用したい時に有効にしてください。 
Disable_All_Functions: false

## === SpigotProtocolHack1.7-1.8 === ##
# [true で有効 | false で無効]
# 初期: false
#SpigotProtocolHack1.7-1.8を使用している場合は有効にしてください。
UseSpigotProtocolHack: false

## === 自動アップデートの設定 === ##
# [true で有効 | false で無効]
# 初期: true
# このプラグインが最新バージョンかチェックします。
# メッセージはOPにしか表示されません。
UpdateChecker: true
AutoDownload: true
OpenTextFile: true

## === メモ帳の設定 === ##
# メモ帳のソフト名を指定します。
# Windowsならnotepadなどです。
SoftName: notepad

## === 曜日表記の設定 === ##
# ここに設定した曜日は%weekで使用されます。
Sunday: '日'
Monday: '月'
Tuesday: '火'
Wednesday: '水'
Thursday: '木'
Friday: '金'
Saturday: '土'

## === 時刻の設定 === ##
# & でカラーコードを使用できます。
# %year で現在の年を取得します。
# %month で現在の月を取得します。
# %day で現在の日にちを取得します。
# %hour で現在の時を取得します。
# %minute で現在の分を取得します。
# %second で現在の秒を取得します。
# %week で現在の曜日を取得します。
# %dayofyear で現在の年の何日目かを取得します。
TimesofDay: '&e%year年%month月%day日%week曜日 %hour時%minute分%second秒'

## === プレイヤーカウントメッセージの設定 === ##
# [true で有効 | false で無効]
# 初期: false
# & でカラーコードを使用できます。
# none でカーソルを合わせても接続中のプレイヤーIdが表示されなくなります。
# %players でサーバーに接続している人数を取得します。
# %maxplayers で最大接続人数を取得します。
# %servername でサーバー名を取得します。
# %version でサーバーのバージョンを取得します。
# %time でTimesofDayに設定した時刻を取得します。
PlayerCountMessage:
  Enable: false
  Message:
  - '&aMinecraft1'
  - '&cMinecraft2'
  - '&eMinecraft3'

## === 最大接続人数の設定 === ##
# [true で有効 | false で無効]
# 初期: true
# 最大接続人数の表示を変更しているだけなので、実際に入れる人数は変わりません。
FakeMaxPlayer:
  Enable: true
  MaxPlayer: 999

## === コマンドメッセージの設定 === ##
# & でカラーコードを使用できます。
# %sender でコマンド実行者を取得します。
# %message でメッセージを取得します。
# %target で指定したプレイヤーを取得します。(tell、tell_targetで使用可能)
Commands:
  Say: '&d[%sender] %message'
  Me: '* %sender %message'
  tell: '[%sender->%target] %message'
  tell_target: '&7%sender whispers %message'

## === サウンドの設定 === ##
# 音を追加したいときは設定の最後に,を入れてください。
# 1.8以前と1.9以降で(音の種類)が変わります。
# 1.9以降の場合はSoundListを参照してください。
# 1.8以前の場合はOldSoundListを参照してください。
# (音の種類)-(音量)-(音の高さ)-(音が鳴る時間)
# none で音を無効化できます。
Sounds:
  KillSound: none
  DeathSound: none
  FirstJoinSound: none
  JoinSound: none
  QuitSound: none
  ChatSound: CHICKEN_EGG_POP-1-1-0
  CommandSound: none
  BanBroadcastSound: none
  KickBroadcastSound: none
  AFKBroadcastSound: none

## === サウンドタイプの設定 === ##
# player でイベントを発生させたプレイヤーに音を再生します。
# allplayers で接続しているプレイヤー全員に音を再生します。
SoundTypes:
  KillSoundType: player
  DeathSoundType: player
  FirstJoinSoundType: player
  JoinSoundType: player
  QuitSoundType: player
  ChatSoundType: allplayers
  CommandSoundType: player
  BanBroadcastSoundType: player
  KickBroadcastSoundType: player
  AFKBroadcastSoundType: player

## === サウンド権限の設定 === ##
# none で全てのプレイヤーに音を再生できます。
# operator でオペレーター権限を持っている人のみ音を再生できます。
# permission でパーミッション権限を持っている人のみ音を再生できます。
SoundAuthoritys:
  KillSoundAuthority: none
  DeathSoundAuthority: none
  FirstJoinSoundAuthority: none
  JoinSoundAuthority: none
  QuitSoundAuthority: none
  ChatSoundAuthority: operator
  CommandSoundAuthority: none
  BanBroadcastSoundAuthority: none
  KickBroadcastSoundAuthority: none
  AFKBroadcastSoundAuthority: none

## === 死亡メッセージの設定 === ##
# [true で有効 | false で無効]
# 初期: false
# & でカラーコードを使用できます。
# %killer でエンティティの名前を取得します。
# %deader で殺害されたプレイヤーを取得します。
# %killer で殺害したエンティティを取得します。(殺害メッセージのみ使用可能です。)
# %weapon で殺害したプレイヤーの武器を取得します。(Playerのみ使用可能です。)
# %time でTimesofDayに設定した時刻を取得します。
DeathMessage:
  Enable: false
  Weapon:
    NullMessage: '素手'
  Messages:
    Drowning: '&c%deaderは死亡しました。死因: 水'
    Fire: '&c%deaderは死亡しました。死因: 炎'
    Fall: '&c%deaderは死亡しました。死因: 落下'
    Void: '&c%deaderは死亡しました。死因: 奈落'
    Lava: '&c%deaderは死亡しました。死因: 溶岩'
    Magic: '&c%deaderは死亡しました。死因: 魔法'
    Suffocation: '&c%deaderは死亡しました。死因: 窒息'
    Projectile: '&c%deaderは死亡しました。死因: 飛び道具'
    Starvation: '&c%deaderは死亡しました。死因: 飢餓'
    Withered: '&c%deaderは死亡しました。死因: ウィザー'
    Explosion: '&c%deaderは死亡しました。死因: 爆発'
    Player: '&c%deaderは%killerに%weaponで殺害されました。'
    ZombiePigman: '&c%deaderはゾンビピッグマンに殺害されました。'
    Zombie: '&c%deaderはゾンビに殺害されました。'
    Husk: '&c%deaderはハスクに殺害されました。'
    CaveSpider: '&c%deaderは洞窟グモに殺害されました。'
    Spider: '&c%deaderはクモに殺害されました。'
    SilverFish: '&c%deaderはシルバーフィッシュに殺害されました。'
    Slime: '&c%deaderはスライムに殺害されました。'
    MagmaCube: '&c%deaderはマグマキューブに殺害されました。'
    EnderMite: '&c%deaderはエンダーマイトに殺害されました。'
    Enderman: '&c%deaderはエンダーマンに殺害されました。'
    EnderDragon: '&c%deaderはエンダードラゴンに殺害されました。'
    IronGolem: '&c%deaderはアイアンゴーレムに殺害されました。'
    Wolf: '&c%deaderはオオカミに殺害されました。'
    PolarBear: '&c%deaderはシロクマに殺害されました。'
    Giant: '&c%deaderはジャイアントに殺害されました。'
    Guardian: '&c%deaderはガーディアンに殺害されました。'
    Wither: '&c%deaderはウィザーに殺害されました。'
    Witch: '&c%deaderはウィッチに殺害されました。'
    Blaze: '&c%deaderはブレイズに殺害されました。'
    Ghast: '&c%deaderはガストに殺害されました。'
    Stray: '&c%deaderはストレイに殺害されました。'
    Skeleton: '&c%deaderはスケルトンに殺害されました。'
    WitherSkeleton: '&c%deaderはウィザースケルトンに殺害されました。'

## === ログイン、ログアウトメッセージの設定 === ##
# [true で有効 | false で無効]
# 初期: true
# & でカラーコードを使用できます。
# %player でプレイヤーを取得します。
# %time でTimesofDayに設定した時刻を取得します。
PlayerJoinQuitMessage:
  Enable: true
  FirstJoinMssage: '&e%playerさんが初めてサーバーに参加しました。'
  JoinMessage: '&e%playerさんがサーバーに参加しました。'
  QuitMessage: '&e%playerさんがサーバーから退出しました。'

## === ログインメッセージの設定 === ##
# [true で有効 | false で無効]
# 初期: false
# & でカラーコードを使用できます。
# %player でプレイヤーを取得します。
# %time でTimesofDayに設定した時刻を取得します。
PlayerLoginMessage:
  Enable: false
  Message:
  - 'アップデート情報: テストです。'

## === アイテム配布の設定 === ##
# [true で有効 | false で無効]
# 初期: false
# Kits導入時のみ動作します。
# キット名を指定することで初ログイン時に配布されます。
FirstJoinItem:
  Enable: false
  KitName: Hunter

## === チャットの設定 === ##
# [true で有効 | false で無効]
# 初期: false
# & でカラーコードを使用できます。
# %player でプレイヤーを取得します。
# %message でプレイヤーのチャットを取得します。
# %time でTimesofDayに設定した時刻を取得します。
ChatMessageFormat:
  Enable: false
  Message: '<&e%player&f> %message'

## === キックメッセージの設定 === ##
# [true で有効 | false で無効]
# 初期: false
# BroadcastMessageはサーバー全体に流れるメッセージです。
# & でカラーコードを使用できます。
# none でメッセージの設定を無効化できます。
# %player でプレイヤーを取得します。
# %reason で理由を取得できます。
# %line で改行することができます。(BroadcastMessage以外で使用可能)
# %time でTimesofDayに設定した時刻を取得します。
PlayerKickMessage:
  Enable: false
  BanMessage: '&cあなたはBanされました。'
  KickMessage: '&eあなたはKickされました。'
  AFKMessage: '&c放置していたためKickされました！'
  BanBroadcastMessage: '&c%playerさんがBanされました！'
  KickBroadcastMessage: '&c%playerさんがKickされました！'
  AFKBroadcastMessage: '&c%playerさんが放置していたためKickされました！'

## === ログインキックメッセージの設定 === ##
# [true で有効 | false で無効]
# 初期: false
# & でカラーコードを使用できます。
# %player でプレイヤーを取得します。
# %line で改行することができます。
# %time でTimesofDayに設定した時刻を取得します。
PlayerLoginKickMessage:
  Enable: false
  BanMessage: '&cBANされているためログインできません。'
  WhiteListMessage: 'ホワイトリストが有効になっているためログインできません。'

## === サーバールールの設定 === ##
# [true で有効 | false で無効]
# 初期: false
# & でカラーコードを使用できます。
Rules:
  Enable: false
  Message:
  - '&b---------&aサーバールール&b---------'
  - '&e楽しんでください'
  - '&e挨拶をしてください'

## === タイトルの表示時間などの設定 === ##
# FadeIn 表示するまでの時間
# Stay 表示している時間
# FadeOut 消えるまでの時間
TitleTime:
  FadeIn: 10
  Stay: 40
  FadeOut: 10

## === タイトルメッセージの設定 === ##
# [true で有効 | false で無効]
# 初期: true
# & でカラーコードを使用できます。
# %player でプレイヤーを取得します。
# %time でTimesofDayに設定した時刻を取得します。
Title:
  Enable: true
  TitleMessage: '&aテスト1'
  SubTitleMessage: '&eテスト2'

## === タブタイトルの設定 === ##
# [true で有効 | false で無効]
# 初期: true
# タブタイトルに %time が含まれているとタイマーがスタートします。
# & でカラーコードを使用できます。
# %player でプレイヤーを取得します。
# %time でTimesofDayに設定した時刻を取得します。
TabTitle:
  Enable: true
  Header: '&dテスト1'
  Footer: '&bテスト2'

## === サーバーアイコンの設定 === ##
# [true で有効 | false で無効]
# 初期: false
# アイコンはServerIconに保存してください。
# ファイルに入れたアイコンをランダムで表示します。
ServerIcon:
  Enable: false

## === Motdの設定 === ##
# [true で有効 | false で無効]
# 初期: true
# 両方有効にしている場合はRandomMotdが優先されます。
# & でカラーコードを使用できます。
# %players でサーバーにログインしている人数を取得します。
# %maxplayers で最大接続人数を取得します。
# %servername でサーバー名を取得します。
# %version でサーバーのバージョンを取得します。
# %time でTimesofDayに設定した時刻を取得します。
RandomMotd:
  Enable: false
  Message:
    test1:
      - '&1ようこそマインクラフトサーバーへ'
      - '&2バージョン%version &3現在サーバーで%players人が遊んでます'
    test2:
      - '&4ようこそマインクラフトサーバーへ'
      - '&5バージョン%version &7現在サーバーで%players人が遊んでます'
Motd:
  Enable: true
  Message:
  - '&bようこそマインクラフトサーバーへ'
  - '&dバージョン%version &6現在サーバーで%players人が遊んでます'