name: CustomMessage
main: com.github.yuttyann.custommessage.Main
version: 5.8
author: yuttyann44581
website: http://ch.nicovideo.jp/yuttyann44581/blomaga/ar810622
softdepend: [ProtocolLib]

commands:
  custommessage:
    description: Config再読み込みコマンド
    usage: /<command> reload - Configの再読み込みをします。
  rules:
    description: ルールコマンド
    usage: /<command> - ルールを表示します。
  ban:
    description: Prevents the specified player from using this server
    usage: /<command> <player> [reason ...]
  me:
    description: Performs the specified action in chat
    usage: /<command> <action>
  say:
    description: Broadcasts the given message as the sender
    usage: /<command> <message ...>
  tell:
    description: Sends a private message to the givenplayer
    usage: /<command> <player> <message>
    aliases: [w, msg]