name: CustomMessage
main: com.github.yuttyann.custommessage.Main
version: 7.1
softdepend: [ProtocolLib, Kits, CrackShot]
author: yuttyann44581
website: http://file.yuttyann44581.net/

commands:
  custommessage:
    description: ルール、タイトル 関係コマンド
    usage: |
           /<command> reload - コンフィグの再読み込みを行います。
           /<command> rules - ルールを表示します。
           /<command> title <player> <title> <subtitle> - 指定したプレイヤーにタイトルを表示します。
           /<command> tabtitle <player> <header> <footer> - 指定したプレイヤーにタブタイトルを表示します。
    aliases: [cmg]
  ban:
    description: Prevents the specified player from using this server
    usage: /<command> <player> [reason ...]
  me:
    description: Performs the specified action in chat
    usage: /<command> <action>
  say:
    description: Broadcasts the given message as the sender
    usage: /<command> <message ...>
  tell:
    description: Sends a private message to the givenplayer
    usage: /<command> <player> <message>
    aliases: [w, msg]