name: CustomMessage
main: com.github.yuttyann.custommessage.Main
version: 6.4
softdepend: [ProtocolLib, Kits, CrackShot]
author: yuttyann44581
website: http://file.yuttyann44581.net/

commands:
  custommessage:
    description: Config再読み込みコマンド
    usage: /<command> reload - Configの再読み込みをします。
  rules:
    description: ルールコマンド
    usage: /<command> - ルールを表示します。
  title:
    description: タイトルコマンド
    usage: |
           /<command> <player> <title> <subtitle> - 指定したプレイヤーにタイトルを表示します。
           /<command> tab <player> <header> <footer> - 指定したプレイヤーにタブタイトルを表示します。
  ban:
    description: Prevents the specified player from using this server
    usage: /<command> <player> [reason ...]
  me:
    description: Performs the specified action in chat
    usage: /<command> <action>
  say:
    description: Broadcasts the given message as the sender
    usage: /<command> <message ...>
  tell:
    description: Sends a private message to the givenplayer
    usage: /<command> <player> <message>
    aliases: [w, msg]